[package]
name = "walk-git"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
env_logger = "0.11.8"
log = { version = "0.4.22", features = [
  "max_level_debug",
  "release_max_level_debug",
] }
walkdir = "2.5.0"
